In [1]:
import numpy as np

In [2]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])
print(ar)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [3]:
print(ar.shape)
print(ar.ndim)
print(ar.size)

(4, 3)
2
12


In [ ]:
print(ar.ndim)

2


In [ ]:
print(ar.size)

2


In [ ]:
ar1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(ar1)
print(ar1.shape)
print(ar1.ndim)
print(ar1.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
3
18


In [ ]:
a=np.arange(18).reshape(3,2,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [ ]:
a.resize(9,2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

Difference between Reshape and Resize

In [ ]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]],dtype=complex)
print(a.dtype)

complex128


In [ ]:
e=np.empty((2,3))
print(e)


[[4.63776389e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
i=np.ones((2,3), dtype=np.int16)
print(i)

[[1 1 1]
 [1 1 1]]


In [ ]:
print(i.size)
print(i.ndim)
print(i.shape)

6
2
(2, 3)


In [ ]:
'''np.linespace
np.random
np.arange
np.flatten'''
c=np.linspace( 3, 4, 9 )
ca=np.arange( 3, 2, 9 )
b=np.linspace( 0, 2, 5 )
ba=np.arange( 0, 2, 5 )
a=np.linspace( 0, 2, 20 )
aa=np.arange( 0, 2, 20 )
print(a ,ca ,b,ba,a,aa, sep='\n') 

[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]
[]
[0.  0.5 1.  1.5 2. ]
[0]
[0.         0.10526316 0.21052632 0.31578947 0.42105263 0.52631579
 0.63157895 0.73684211 0.84210526 0.94736842 1.05263158 1.15789474
 1.26315789 1.36842105 1.47368421 1.57894737 1.68421053 1.78947368
 1.89473684 2.        ]
[0]


In [ ]:
a=np.arange(0,15,5)
print(a)

[ 0  5 10]


In [ ]:
ar1=np.arange(0,60,10)
print(ar1)
print(ar1.reshape(3,2))
ar1.resize(2,3)
print(ar1)

[ 0 10 20 30 40 50]
[[ 0 10]
 [20 30]
 [40 50]]
[[ 0 10 20]
 [30 40 50]]


In [ ]:
ar2=np.random.random((2,3))
print(ar2)

[[0.46139808 0.96544812 0.09759434]
 [0.05064436 0.3324176  0.25234246]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flarr = arr.flatten() 
  
print ("\nOriginal array:\n", arr) 
print ("Fattened array:\n", flarr) 


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [ ]:
k=np.zeros((4,5))
print(k)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
